import { BookmarkItem } from "./types";

export const INITIAL_COLLECTIONS: string[] = [
  "All",
  "Real Property Tax",
  "Treasury Auditing",
  "Urgent Reference",
  "General Operations",
];

export const SEED_BOOKMARKS: BookmarkItem[] = [
  {
    id: "bm-1",
    title: "LGU Real Property Assessment Advisory Guidelines and Valuation Standards",
    orderNo: "BLGF-DO-2024-018",
    seriesYear: 2024,
    category: "Assessment Regulations",
    clearance: "Public",
    dateBookmarked: "2024-08-29",
    officialDate: "2024-08-15",
    collection: "Real Property Tax",
    personalNotes: "Check Section 4.1 for the 2% monthly interest cap during quarterly tax enforcement hearings.",
    tags: ["Valuation", "Penalties", "2024 Update"],
    shelfLocation: {
      cabinet: "Cabinet A",
      shelf: "Shelf 2",
      binder: "Binder 04",
      barcode: "LOC-A2-B04",
    },
    fileSize: "4.8 MB",
    pageCount: 28,
    isPinned: true,
  },
  {
    id: "bm-2",
    title: "Treasury Circular on Local Revenue Collections and Automation Protocols",
    orderNo: "TC-2024-009",
    seriesYear: 2024,
    category: "Treasury Advisories",
    clearance: "Public",
    dateBookmarked: "2024-08-25",
    officialDate: "2024-07-20",
    collection: "Treasury Auditing",
    personalNotes: "Directives for e-receipting and automatic daily cash reconciliation with LandBank depositories.",
    tags: ["Remittance", "E-Receipts", "Audit"],
    shelfLocation: {
      cabinet: "Cabinet B",
      shelf: "Shelf 1",
      binder: "Binder 02",
      barcode: "LOC-B1-B02",
    },
    fileSize: "2.3 MB",
    pageCount: 14,
    isPinned: true,
  },
  {
    id: "bm-3",
    title: "Electronic Real Property Tax Payment System Integration Standards",
    orderNo: "DOF-DO-2023-042",
    seriesYear: 2023,
    category: "Revenue Operations",
    clearance: "Internal",
    dateBookmarked: "2024-08-10",
    officialDate: "2023-11-12",
    collection: "Real Property Tax",
    personalNotes: "Reference for online payment gateway fee absorption limits by the municipal treasury.",
    tags: ["Online Payment", "Gateways", "DOF"],
    shelfLocation: {
      cabinet: "Cabinet A",
      shelf: "Shelf 3",
      binder: "Binder 01",
      barcode: "LOC-A3-B01",
    },
    fileSize: "3.6 MB",
    pageCount: 22,
    isPinned: false,
  },
  {
    id: "bm-4",
    title: "Omnibus Guidelines on Delinquent Tax Auction Proceedings and Notice Compliance",
    orderNo: "MC-2023-112",
    seriesYear: 2023,
    category: "Assessment Regulations",
    clearance: "Public",
    dateBookmarked: "2024-07-18",
    officialDate: "2023-09-05",
    collection: "Urgent Reference",
    personalNotes: "Statutory 30-day publication timeline before proceeding with public auction of seized real properties.",
    tags: ["Auction", "Delinquency", "Publication"],
    shelfLocation: {
      cabinet: "Cabinet C",
      shelf: "Shelf 1",
      binder: "Binder 06",
      barcode: "LOC-C1-B06",
    },
    fileSize: "5.1 MB",
    pageCount: 36,
    isPinned: true,
  },
  {
    id: "bm-5",
    title: "Revised Qualifications and Continuing Credentialing for Local Assessment Officers",
    orderNo: "BLGF-MC-2024-005",
    seriesYear: 2024,
    category: "General Operations",
    clearance: "Public",
    dateBookmarked: "2024-06-12",
    officialDate: "2024-05-18",
    collection: "General Operations",
    personalNotes: "Required CPD credit units for annual assessor certification renewal.",
    tags: ["Staffing", "CPD", "Licensing"],
    shelfLocation: {
      cabinet: "Cabinet D",
      shelf: "Shelf 2",
      binder: "Binder 03",
      barcode: "LOC-D2-B03",
    },
    fileSize: "1.9 MB",
    pageCount: 10,
    isPinned: false,
  },
  {
    id: "bm-6",
    title: "Cash Remittance Schedules and Authorized Banking Depositories for Treasurers",
    orderNo: "TC-2023-014",
    seriesYear: 2023,
    category: "Treasury Advisories",
    clearance: "Restricted",
    dateBookmarked: "2024-05-30",
    officialDate: "2023-04-10",
    collection: "Treasury Auditing",
    personalNotes: "Overnight vault cash ceiling limits for 1st and 2nd class municipalities.",
    tags: ["Vault Limit", "Cash Handling", "Banking"],
    shelfLocation: {
      cabinet: "Cabinet B",
      shelf: "Shelf 2",
      binder: "Binder 05",
      barcode: "LOC-B2-B05",
    },
    fileSize: "2.7 MB",
    pageCount: 16,
    isPinned: false,
  },
];
