"""create documents table

Revision ID: 19fe64558312
Revises: 5b2b166e0480
Create Date: 2026-07-29 10:43:59.150083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19fe64558312'
down_revision: Union[str, Sequence[str], None] = '5b2b166e0480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
