"""add_document_parent_chunks_and_parent_chunk_id

Revision ID: ba27ae171bd3
Revises: e2a4b8c9d10e
Create Date: 2026-10-02 14:36:28.008059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba27ae171bd3'
down_revision: Union[str, Sequence[str], None] = 'e2a4b8c9d10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_parent_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=100), nullable=False),
    sa.Column('section_title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_parent_chunks_document_version_id'), 'document_parent_chunks', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_parent_chunks_parent_id'), 'document_parent_chunks', ['parent_id'], unique=False)
    op.alter_column('chat_messages', 'task_type',
               existing_type=postgresql.ENUM('summarization', 'comparison', 'extraction', 'inconsistency_check', 'report_gen', name='conversation_chat_type'),
               nullable=True)
    op.add_column('document_chunks', sa.Column('parent_chunk_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_document_chunks_parent_chunk_id'), 'document_chunks', ['parent_chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_parent_chunk_id'), table_name='document_chunks')
    op.drop_column('document_chunks', 'parent_chunk_id')
    op.alter_column('chat_messages', 'task_type',
               existing_type=postgresql.ENUM('summarization', 'comparison', 'extraction', 'inconsistency_check', 'report_gen', name='conversation_chat_type'),
               nullable=False)
    op.drop_index(op.f('ix_document_parent_chunks_parent_id'), table_name='document_parent_chunks')
    op.drop_index(op.f('ix_document_parent_chunks_document_version_id'), table_name='document_parent_chunks')
    op.drop_table('document_parent_chunks')
    # ### end Alembic commands ###
