"""create documents table

Revision ID: d116e4ff4e7d
Revises: 16bb7afce936
Create Date: 2026-08-22 11:44:39.819155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd116e4ff4e7d'
down_revision: Union[str, Sequence[str], None] = '16bb7afce936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('input_params', sa.JSON(), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_bench_marks_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eval_type', sa.Enum('retrieval_accuracy', 'task_completion', 'response_quality', 'processing_speed', name='agent_tasks_enum'), nullable=True),
    sa.Column('precision_at_k', sa.Float(), nullable=False),
    sa.Column('recall_at_k', sa.Float(), nullable=False),
    sa.Column('mrr_score', sa.Float(), nullable=False),
    sa.Column('tasks_completion_rate', sa.Float(), nullable=False),
    sa.Column('average_latency_ms', sa.Float(), nullable=False),
    sa.Column('test_dataset_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_analytics_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('division', sa.String(length=255), nullable=False),
    sa.Column('document_category_id', sa.Integer(), nullable=False),
    sa.Column('metric_data', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('is_actionable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_category_id'], ['document_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_type', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('summarization', 'comparison', 'extraction', 'inconsistency_check', 'report_gen', name='conversation_chat_type'), nullable=False),
    sa.Column('agent_reasoning_chain', sa.JSON(), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.Enum('summary', 'comparison', 'inconsistency_audit', 'analytics_summary', name='generated_reports_enum'), nullable=True),
    sa.Column('report_content', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('cited_text_snippet', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_version.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages_sources')
    op.drop_table('generated_reports')
    op.drop_table('chat_messages')
    op.drop_table('conversation')
    op.drop_table('ml_analytics_insights')
    op.drop_table('evaluation_bench_marks_runs')
    op.drop_table('agent_executions')
    # ### end Alembic commands ###
