"""add_unique_constraints_for_idempotency

Revision ID: e77e65ec6f7b
Revises: ba27ae171bd3
Create Date: 2026-10-02 15:20:59.352850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77e65ec6f7b'
down_revision: Union[str, Sequence[str], None] = 'ba27ae171bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_chunks_version_chunk_index', 'document_chunks', ['document_version_id', 'chunk_index'])
    op.create_unique_constraint('uq_document_parent_chunks_version_parent_id', 'document_parent_chunks', ['document_version_id', 'parent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_parent_chunks_version_parent_id', 'document_parent_chunks', type_='unique')
    op.drop_constraint('uq_document_chunks_version_chunk_index', 'document_chunks', type_='unique')
    # ### end Alembic commands ###
